import type { WorkflowTemplate } from '../types'

function id(seed: string) {
  return seed.replace(/[^a-z0-9]/gi, '-').toLowerCase()
}

export const aiNativeTemplate: WorkflowTemplate = {
  id: 'ai-native-full-stack',
  name: 'AI-Native Full Stack',
  description: 'Three focused workflows covering discovery/requirements, development, and delivery. Uses Claude Code, Cursor, GitHub Actions, and Vercel.',
  icon: '🤖',
  tags: ['claude', 'cursor', 'github-actions', 'vercel', 'full-stack'],
  workspace: {
    id: id('ai-native-workspace'),
    name: 'AI-Native Full Stack',
    description: 'Standard product lifecycle for AI-native engineering teams.',
    team: '',
    version: '1.0.0',
    workflows: [
      {
        id: id('discovery-requirements'),
        name: 'Discovery & Requirements',
        version: '1.0.0',
        team: '',
        description: 'User research, design, and PRD drafting. Load when working on discovery or scoping work.',
        tags: ['discovery', 'ux', 'requirements'],
        dependsOn: [],
        steps: [
          {
            id: id('problem-framing'),
            type: 'step',
            name: 'Problem Framing',
            description: 'Define the problem space and identify user needs.',
            inputs: ['Market signals', 'Customer feedback', 'Competitor analysis'],
            outputs: ['Problem statement', 'Opportunity brief'],
            agents: [{ id: id('ag-opus'), name: 'Claude Opus', model: 'claude-opus-4-7', skills: ['research', 'synthesize', 'critique'], harness: 'claude-code' }],
            tools: [
              { id: id('notion'), name: 'Notion', type: 'saas', required: true, alternatives: ['Confluence', 'Linear'] },
              { id: id('perplexity'), name: 'Perplexity', type: 'ai-tool', required: false, alternatives: ['ChatGPT'] },
            ],
            actor: 'either',
            enforcement: 'required',
            notes: '',
            position: { x: 0, y: 0 },
          },
          {
            id: id('research-synthesis'),
            type: 'step',
            name: 'Research Synthesis',
            description: 'Synthesize user interviews and analytics into insights.',
            inputs: ['Interview recordings', 'Analytics exports', 'Support tickets'],
            outputs: ['Insight brief', 'User journey map'],
            agents: [{ id: id('ag-sonnet'), name: 'Claude Sonnet', model: 'claude-sonnet-4-6', skills: ['summarize', 'extract-themes'], harness: 'claude-code' }],
            tools: [
              { id: id('notion-d'), name: 'Notion', type: 'saas', required: true, alternatives: ['Miro'] },
              { id: id('dovetail'), name: 'Dovetail', type: 'saas', required: false, alternatives: ['Maze', 'UserTesting'] },
            ],
            actor: 'either',
            enforcement: 'required',
            notes: '',
            position: { x: 280, y: 0 },
          },
          {
            id: id('design-direction'),
            type: 'step',
            name: 'Design Direction',
            description: 'Define UX flows and visual direction.',
            inputs: ['Insight brief', 'Brand guidelines'],
            outputs: ['Wireframes', 'Design spec'],
            agents: [],
            tools: [{ id: id('figma'), name: 'Figma', type: 'saas', required: true, alternatives: ['Sketch', 'Penpot'] }],
            actor: 'human',
            enforcement: 'recommended',
            notes: '',
            position: { x: 560, y: 0 },
          },
          {
            id: id('prd'),
            type: 'agent',
            name: 'PRD Drafting',
            description: 'Draft product requirements with Claude assistance.',
            inputs: ['Opportunity brief', 'Design spec', 'User journey map'],
            outputs: ['PRD', 'Acceptance criteria'],
            agents: [{ id: id('ag-sonnet-r'), name: 'Claude Sonnet', model: 'claude-sonnet-4-6', skills: ['write', 'structure', 'critique'], harness: 'claude-code' }],
            tools: [{ id: id('linear'), name: 'Linear', type: 'saas', required: true, alternatives: ['Jira', 'GitHub Issues'] }],
            actor: 'agent',
            enforcement: 'required',
            notes: '',
            position: { x: 0, y: 180 },
          },
        ],
      },
      {
        id: id('development'),
        name: 'Development',
        version: '1.0.0',
        team: '',
        description: 'AI-assisted feature development, code review, and testing. Load when writing code.',
        tags: ['dev', 'claude-code', 'cursor', 'testing'],
        dependsOn: [id('discovery-requirements')],
        steps: [
          {
            id: id('local-env'),
            type: 'local-config',
            name: 'Local Environment',
            description: 'Configure dev environment and install dependencies.',
            inputs: ['README', 'Package manifests'],
            outputs: ['Running dev server'],
            agents: [],
            tools: [
              { id: id('cursor'), name: 'Cursor', type: 'ide', required: false, alternatives: ['VS Code', 'JetBrains'] },
              { id: id('nvm'), name: 'nvm', type: 'cli', required: false, alternatives: ['fnm', 'mise'] },
            ],
            actor: 'human',
            enforcement: 'required',
            notes: '',
            position: { x: 0, y: 0 },
          },
          {
            id: id('feature-dev'),
            type: 'agent',
            name: 'Feature Development',
            description: 'Implement features with Claude Code in the loop.',
            inputs: ['Acceptance criteria', 'Design spec'],
            outputs: ['Feature branch', 'PR'],
            agents: [{ id: id('ag-cc'), name: 'Claude Code', model: 'claude-sonnet-4-6', skills: ['code', 'refactor', 'test'], harness: 'claude-code' }],
            tools: [
              { id: id('cursor-dev'), name: 'Cursor', type: 'ide', required: false, alternatives: ['VS Code + Copilot'] },
              { id: id('github'), name: 'GitHub', type: 'saas', required: true, alternatives: ['GitLab'] },
            ],
            actor: 'either',
            enforcement: 'required',
            notes: '',
            position: { x: 280, y: 0 },
          },
          {
            id: id('unit-tests'),
            type: 'step',
            name: 'Unit & Integration Tests',
            description: 'Run automated test suite; generate missing coverage.',
            inputs: ['Feature branch', 'Test specs'],
            outputs: ['Test report', 'Coverage report'],
            agents: [{ id: id('ag-cc-t'), name: 'Claude Code', model: 'claude-sonnet-4-6', skills: ['write-tests', 'debug'], harness: 'claude-code' }],
            tools: [
              { id: id('vitest'), name: 'Vitest', type: 'cli', required: false, alternatives: ['Jest', 'pytest'] },
              { id: id('playwright'), name: 'Playwright', type: 'cli', required: false, alternatives: ['Cypress'] },
            ],
            actor: 'agent',
            enforcement: 'required',
            notes: '',
            position: { x: 560, y: 0 },
          },
        ],
      },
      {
        id: id('delivery'),
        name: 'Delivery',
        version: '1.0.0',
        team: '',
        description: 'Deployment, CI/CD pipelines, and monitoring. Load when shipping or debugging production.',
        tags: ['deployment', 'ci-cd', 'vercel', 'monitoring'],
        dependsOn: [id('development')],
        steps: [
          {
            id: id('ci-pipeline'),
            type: 'step',
            name: 'CI Pipeline',
            description: 'Lint, test, build on every PR.',
            inputs: ['Pull request'],
            outputs: ['CI status', 'Build artifact'],
            agents: [],
            tools: [{ id: id('gha-ci'), name: 'GitHub Actions', type: 'cli', required: true, alternatives: [] }],
            actor: 'agent',
            enforcement: 'required',
            notes: '',
            position: { x: 0, y: 0 },
          },
          {
            id: id('preview'),
            type: 'step',
            name: 'Preview Deployment',
            description: 'Deploy PR preview for stakeholder review.',
            inputs: ['Approved PR'],
            outputs: ['Preview URL'],
            agents: [],
            tools: [{ id: id('vercel'), name: 'Vercel', type: 'saas', required: false, alternatives: ['Netlify', 'Render', 'Fly.io'] }],
            actor: 'agent',
            enforcement: 'recommended',
            notes: '',
            position: { x: 280, y: 0 },
          },
          {
            id: id('production'),
            type: 'step',
            name: 'Production Deploy',
            description: 'Merge to main and trigger production pipeline.',
            inputs: ['Preview URL', 'Stakeholder sign-off'],
            outputs: ['Production release'],
            agents: [],
            tools: [
              { id: id('vercel-prod'), name: 'Vercel', type: 'saas', required: false, alternatives: ['AWS', 'GCP'] },
              { id: id('gha'), name: 'GitHub Actions', type: 'cli', required: true, alternatives: ['CircleCI'] },
            ],
            actor: 'human',
            enforcement: 'required',
            notes: 'Requires explicit sign-off before merging to main.',
            position: { x: 560, y: 0 },
          },
          {
            id: id('monitoring'),
            type: 'step',
            name: 'Monitoring',
            description: 'Track errors, latency, and model performance.',
            inputs: ['Production release'],
            outputs: ['Dashboards', 'Alerts'],
            agents: [],
            tools: [{ id: id('datadog'), name: 'Datadog', type: 'saas', required: false, alternatives: ['Grafana', 'Sentry', 'Honeycomb'] }],
            actor: 'either',
            enforcement: 'recommended',
            notes: '',
            position: { x: 840, y: 0 },
          },
        ],
      },
    ],
  },
}
