import type { WorkflowTemplate } from '../types'

function id(seed: string) {
  return seed.replace(/[^a-z0-9]/gi, '-').toLowerCase()
}

export const dataScienceTemplate: WorkflowTemplate = {
  id: 'data-science-ml',
  name: 'Data Science / ML',
  description: 'Two workflows: Data & Features, then Training & Serving. Uses Jupyter, MLflow, HuggingFace, and LLM-assisted analysis.',
  icon: '🧠',
  tags: ['jupyter', 'mlflow', 'huggingface', 'dvc', 'python'],
  workspace: {
    id: id('ds-workspace'),
    name: 'Data Science / ML',
    description: 'End-to-end ML workflow with LLM-assisted analysis and model development.',
    team: '',
    version: '1.0.0',
    workflows: [
      {
        id: id('data-features'),
        name: 'Data & Features',
        version: '1.0.0',
        team: '',
        description: 'Problem scoping, data exploration, and feature engineering. Load when working on data pipelines.',
        tags: ['data', 'eda', 'features', 'jupyter'],
        dependsOn: [],
        steps: [
          {
            id: id('ml-problem'),
            type: 'step',
            name: 'ML Problem Definition',
            description: 'Define task type, target metric, and baseline.',
            inputs: ['Business requirement', 'Historical data sample'],
            outputs: ['ML problem spec', 'Success criteria'],
            agents: [{ id: id('ag-opus'), name: 'Claude Opus', model: 'claude-opus-4-7', skills: ['analyze', 'structure'], harness: 'claude-code' }],
            tools: [{ id: id('jupyter-s'), name: 'Jupyter', type: 'ide', required: false, alternatives: ['Colab', 'Marimo'] }],
            actor: 'human',
            enforcement: 'required',
            notes: 'Task framing and success criteria require domain expertise and stakeholder alignment.',
            position: { x: 0, y: 0 },
          },
          {
            id: id('eda'),
            type: 'step',
            name: 'Exploratory Data Analysis',
            description: 'Profile, visualize, and understand data distributions.',
            inputs: ['Raw dataset', 'ML problem spec'],
            outputs: ['EDA notebook', 'Data quality report'],
            agents: [{ id: id('ag-s-eda'), name: 'Claude Sonnet', model: 'claude-sonnet-4-6', skills: ['analyze', 'code', 'visualize'], harness: 'claude-code' }],
            tools: [
              { id: id('jupyter-e'), name: 'Jupyter', type: 'ide', required: true, alternatives: ['Colab', 'VS Code'] },
              { id: id('pandas'), name: 'pandas', type: 'sdk', required: true, alternatives: ['polars', 'duckdb'] },
            ],
            actor: 'either',
            enforcement: 'required',
            notes: '',
            position: { x: 280, y: 0 },
          },
          {
            id: id('data-ver'),
            type: 'local-config',
            name: 'Data Versioning',
            description: 'Track dataset versions for reproducible pipelines.',
            inputs: ['Raw dataset'],
            outputs: ['DVC pipeline', 'Remote storage config'],
            agents: [],
            tools: [
              { id: id('dvc'), name: 'DVC', type: 'cli', required: false, alternatives: ['LakeFS', 'Delta Lake'] },
              { id: id('s3'), name: 'S3', type: 'saas', required: false, alternatives: ['GCS', 'Azure Blob'] },
            ],
            actor: 'human',
            enforcement: 'recommended',
            notes: '',
            position: { x: 560, y: 0 },
          },
          {
            id: id('feat-eng'),
            type: 'step',
            name: 'Feature Pipeline',
            description: 'Build and validate feature transformations.',
            inputs: ['EDA notebook', 'Data quality report'],
            outputs: ['Feature store', 'Feature documentation'],
            agents: [{ id: id('ag-s-feat'), name: 'Claude Sonnet', model: 'claude-sonnet-4-6', skills: ['code', 'review'], harness: 'claude-code' }],
            tools: [{ id: id('sklearn'), name: 'scikit-learn', type: 'sdk', required: false, alternatives: ['Feast', 'Tecton'] }],
            actor: 'either',
            enforcement: 'required',
            notes: '',
            position: { x: 840, y: 0 },
          },
        ],
      },
      {
        id: id('training-serving'),
        name: 'Training & Serving',
        version: '1.0.0',
        team: '',
        description: 'Model training, evaluation, and production serving. Load when working on model quality or deployment.',
        tags: ['training', 'mlflow', 'huggingface', 'serving', 'docker'],
        dependsOn: [id('data-features')],
        steps: [
          {
            id: id('experiments'),
            type: 'step',
            name: 'Experiment Runs',
            description: 'Train and track model experiments with hyperparameter search.',
            inputs: ['Feature store', 'ML problem spec'],
            outputs: ['Trained models', 'Experiment logs'],
            agents: [{ id: id('ag-s-train'), name: 'Claude Sonnet', model: 'claude-sonnet-4-6', skills: ['debug', 'code', 'suggest-hyperparams'], harness: 'claude-code' }],
            tools: [
              { id: id('mlflow'), name: 'MLflow', type: 'saas', required: false, alternatives: ['W&B', 'CometML', 'Neptune'] },
              { id: id('hf-train'), name: 'HuggingFace', type: 'sdk', required: false, alternatives: ['PyTorch Lightning', 'Keras'] },
            ],
            actor: 'either',
            enforcement: 'required',
            notes: '',
            position: { x: 0, y: 0 },
          },
          {
            id: id('model-eval'),
            type: 'step',
            name: 'Model Evaluation',
            description: 'Measure performance on held-out test set, check for bias.',
            inputs: ['Trained models', 'Test dataset'],
            outputs: ['Evaluation report', 'Model card'],
            agents: [{ id: id('ag-s-eval'), name: 'Claude Sonnet', model: 'claude-sonnet-4-6', skills: ['analyze', 'write-report'], harness: 'claude-code' }],
            tools: [{ id: id('mlflow-ev'), name: 'MLflow', type: 'saas', required: false, alternatives: ['W&B', 'Evidently'] }],
            actor: 'either',
            enforcement: 'required',
            notes: '',
            position: { x: 280, y: 0 },
          },
          {
            id: id('deploy-model'),
            type: 'step',
            name: 'Model Deployment',
            description: 'Containerize and deploy the model behind an API.',
            inputs: ['Trained model', 'Model card'],
            outputs: ['Model API endpoint', 'Monitoring dashboard'],
            agents: [],
            tools: [
              { id: id('hf-hub'), name: 'HuggingFace Hub', type: 'saas', required: false, alternatives: ['BentoML', 'Seldon', 'Ray Serve'] },
              { id: id('docker'), name: 'Docker', type: 'cli', required: true, alternatives: [] },
            ],
            actor: 'human',
            enforcement: 'required',
            notes: '',
            position: { x: 560, y: 0 },
          },
        ],
      },
    ],
  },
}
