import type { WorkflowTemplate } from '../types'

function id(seed: string) {
  return seed.replace(/[^a-z0-9]/gi, '-').toLowerCase()
}

export const llmApiProductTemplate: WorkflowTemplate = {
  id: 'llm-api-product',
  name: 'LLM API Product',
  description: 'Two workflows: Prompt Engineering & Evals, then Deployment & Observability. For teams building on LLM APIs.',
  icon: '⚡',
  tags: ['anthropic', 'api', 'evals', 'prompting', 'observability'],
  workspace: {
    id: id('llm-api-workspace'),
    name: 'LLM API Product',
    description: 'Workflow for teams building products on top of LLM APIs.',
    team: '',
    version: '1.0.0',
    workflows: [
      {
        id: id('prompt-evals'),
        name: 'Prompt Engineering & Evals',
        version: '1.0.0',
        team: '',
        description: 'Design, iterate, and evaluate prompts. Load when working on AI capability quality.',
        tags: ['prompting', 'evals', 'quality'],
        dependsOn: [],
        steps: [
          {
            id: id('cap-design'),
            type: 'step',
            name: 'Capability Scoping',
            description: 'Define what the AI feature should do and what it should not do.',
            inputs: ['User stories', 'Product brief'],
            outputs: ['Capability spec', 'Safety boundaries'],
            ai: [{ id: id('ag-opus'), name: 'Claude Opus', model: 'claude-opus-4-7', skills: ['critique', 'structure'], harness: 'claude-code' }],
            tools: [{ id: id('notion'), name: 'Notion', type: 'saas', required: false, alternatives: ['Google Docs'] }],
            actor: 'either',
            enforcement: 'required',
            notes: '',
            position: { x: 0, y: 0 },
          },
          {
            id: id('prompt-draft'),
            type: 'agent',
            name: 'Prompt Drafting',
            description: 'Write initial system prompt with role, context, and constraints.',
            inputs: ['Capability spec', 'Example inputs/outputs'],
            outputs: ['System prompt v1', 'Few-shot examples'],
            ai: [{ id: id('ag-claude'), name: 'Claude Sonnet', model: 'claude-sonnet-4-6', skills: ['write', 'critique'], harness: 'claude-code' }],
            tools: [{ id: id('console'), name: 'Anthropic Console', type: 'saas', required: false, alternatives: ['OpenAI Playground'] }],
            actor: 'agent',
            enforcement: 'required',
            notes: '',
            position: { x: 280, y: 0 },
          },
          {
            id: id('prompt-iter'),
            type: 'step',
            name: 'Prompt Iteration',
            description: 'Test edge cases and refine with real examples.',
            inputs: ['System prompt v1', 'Test cases'],
            outputs: ['Refined prompt', 'Failure log'],
            ai: [{ id: id('ag-claude2'), name: 'Claude Sonnet', model: 'claude-sonnet-4-6', skills: ['evaluate', 'compare'], harness: 'claude-code' }],
            tools: [{ id: id('promptfoo'), name: 'Promptfoo', type: 'cli', required: false, alternatives: ['RAGAS', 'DeepEval'] }],
            actor: 'either',
            enforcement: 'recommended',
            notes: '',
            position: { x: 560, y: 0 },
          },
          {
            id: id('eval-design'),
            type: 'step',
            name: 'Eval Design',
            description: 'Define quality metrics and create golden test dataset.',
            inputs: ['Refined prompt', 'Failure log'],
            outputs: ['Eval dataset', 'Metric definitions'],
            ai: [],
            tools: [
              { id: id('judge'), name: 'Claude as Judge', type: 'ai-tool', required: false, alternatives: ['GPT-4 as Judge'] },
              { id: id('braintrust'), name: 'Braintrust', type: 'saas', required: false, alternatives: ['LangSmith', 'Phoenix'] },
            ],
            actor: 'human',
            enforcement: 'required',
            notes: 'Metric definitions require human judgment to ensure they reflect real quality.',
            position: { x: 840, y: 0 },
          },
          {
            id: id('ci-evals'),
            type: 'step',
            name: 'CI Evals',
            description: 'Run evals in CI to catch regressions on prompt changes.',
            inputs: ['Eval dataset', 'System prompt'],
            outputs: ['Eval score', 'Regression report'],
            ai: [],
            tools: [
              { id: id('gha-evals'), name: 'GitHub Actions', type: 'cli', required: true, alternatives: [] },
              { id: id('bt2'), name: 'Braintrust', type: 'saas', required: false, alternatives: ['LangSmith'] },
            ],
            actor: 'agent',
            enforcement: 'recommended',
            notes: '',
            position: { x: 0, y: 180 },
          },
        ],
      },
      {
        id: id('api-deploy-obs'),
        name: 'Deployment & Observability',
        version: '1.0.0',
        team: '',
        description: 'Build the API, deploy, and monitor. Load when shipping or debugging production issues.',
        tags: ['api', 'deployment', 'observability', 'cost-tracking'],
        dependsOn: [id('prompt-evals')],
        steps: [
          {
            id: id('api-layer'),
            type: 'step',
            name: 'API Layer',
            description: 'Build the server route, SDK integration, and streaming support.',
            inputs: ['System prompt', 'API design doc'],
            outputs: ['Working API endpoint', 'OpenAPI spec'],
            ai: [{ id: id('ag-cc'), name: 'Claude Code', model: 'claude-sonnet-4-6', skills: ['code', 'test'], harness: 'claude-code' }],
            tools: [
              { id: id('sdk'), name: 'Anthropic SDK', type: 'sdk', required: true, alternatives: ['LiteLLM', 'OpenAI SDK'] },
              { id: id('cursor-api'), name: 'Cursor', type: 'ide', required: false, alternatives: ['VS Code'] },
            ],
            actor: 'agent',
            enforcement: 'required',
            notes: '',
            position: { x: 0, y: 0 },
          },
          {
            id: id('api-deploy'),
            type: 'step',
            name: 'API Deployment',
            description: 'Deploy to serverless or container platform with secrets management.',
            inputs: ['Working API endpoint', 'Environment config'],
            outputs: ['Production API URL', 'API keys'],
            ai: [],
            tools: [
              { id: id('vercel-api'), name: 'Vercel', type: 'saas', required: false, alternatives: ['Fly.io', 'Railway', 'AWS Lambda'] },
              { id: id('infisical'), name: 'Infisical', type: 'saas', required: false, alternatives: ['AWS Secrets Manager', 'Doppler'] },
            ],
            actor: 'human',
            enforcement: 'required',
            notes: '',
            position: { x: 280, y: 0 },
          },
          {
            id: id('llm-obs'),
            type: 'step',
            name: 'LLM Observability',
            description: 'Track token usage, latency, error rates, and eval scores.',
            inputs: ['Production traffic'],
            outputs: ['Cost dashboard', 'Quality dashboard'],
            ai: [],
            tools: [
              { id: id('langsmith'), name: 'LangSmith', type: 'saas', required: false, alternatives: ['Phoenix', 'Braintrust', 'Honeycomb'] },
              { id: id('dd-obs'), name: 'Datadog', type: 'saas', required: false, alternatives: ['Grafana', 'Sentry'] },
            ],
            actor: 'either',
            enforcement: 'recommended',
            notes: '',
            position: { x: 560, y: 0 },
          },
        ],
      },
    ],
  },
}
